server:
  port: 8082

company:
  name2: itheima2

# 设置自定义的静态资源路径
# 方式1：自定义静态资源的路径，会覆盖默认的路径 /resources/ 、 /public/  、 /META-INF/resources/ 、 /static/
#spring:
#  resources:
#    static-locations: classpath:/web/
# 方式2：自定义访问静态资源的url通配 ，如下，必须以web开头的url才能访问静态资源
# eg: http://localhost:8080/2.jpg
# http://localhost:8082/web/2.jpg
spring:
  mvc:
    static-path-pattern: /web/**
